"""Initial schema

Revision ID: b07ee9e411b8
Revises: 
Create Date: 2020-05-27 21:42:31.584593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07ee9e411b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('last_fetch', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=2083), nullable=True),
    sa.Column('aggregated_score', sa.Float(), nullable=True),
    sa.Column('aggregated_certainty', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=2083), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('predicted_certainty', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('rss_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=2083), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_has_category',
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], )
    )
    op.create_table('source_has_tag',
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=2083), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['rss_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_has_category',
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], )
    )
    op.create_table('content_has_tag',
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_has_tag')
    op.drop_table('content_has_category')
    op.drop_table('article')
    op.drop_table('source_has_tag')
    op.drop_table('source_has_category')
    op.drop_table('rss_source')
    op.drop_table('content')
    op.drop_table('tag')
    op.drop_table('source')
    op.drop_table('category')
    op.drop_table('author')
    # ### end Alembic commands ###
