"""Change source id type

Revision ID: d2e64fb746e4
Revises: 9f90c7bac550
Create Date: 2020-04-16 12:10:34.500075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e64fb746e4'
down_revision = '9f90c7bac550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
