"""Change source has category id types

Revision ID: ddf7bd9858bd
Revises: d2e64fb746e4
Create Date: 2020-04-16 12:11:44.927971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf7bd9858bd'
down_revision = 'd2e64fb746e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
