"""Added rss_article_source

Revision ID: 44bb554cfcf2
Revises: a1e4bfc37b25
Create Date: 2020-04-16 14:57:56.670414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44bb554cfcf2'
down_revision = 'a1e4bfc37b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_article_source',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('article', sa.Column('body', sa.String(), nullable=True))
    op.add_column('source', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'type')
    op.drop_column('article', 'body')
    op.drop_table('rss_article_source')
    # ### end Alembic commands ###
