"""Change tablenames to singular

Revision ID: a06c031a3d85
Revises: be5f1938cac7
Create Date: 2020-04-16 11:02:04.980938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06c031a3d85'
down_revision = 'be5f1938cac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('aggregated_score', sa.Float(), nullable=True),
    sa.Column('aggregated_certainty', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('predicted_certainty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contents')
    op.drop_table('sources')
    op.drop_table('authors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.Column('published_date', sa.DATETIME(), nullable=False),
    sa.Column('updated_date', sa.DATETIME(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('aggregated_certainty', sa.FLOAT(), nullable=True),
    sa.Column('aggregated_score', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.Column('published_date', sa.DATETIME(), nullable=False),
    sa.Column('updated_date', sa.DATETIME(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('predicted_certainty', sa.FLOAT(), nullable=True),
    sa.Column('predicted_score', sa.FLOAT(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('content')
    op.drop_table('source')
    op.drop_table('author')
    # ### end Alembic commands ###
