"""Added Article table

Revision ID: a1e4bfc37b25
Revises: ddf7bd9858bd
Create Date: 2020-04-16 13:06:42.384942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e4bfc37b25'
down_revision = 'ddf7bd9858bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_has_tag',
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('tag_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.create_table('article',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('id_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_has_category',
    sa.Column('content_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], )
    )
    op.create_table('content_has_tag',
    sa.Column('content_id', sa.String(), nullable=True),
    sa.Column('tag_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.add_column('content', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'type')
    op.drop_table('content_has_tag')
    op.drop_table('content_has_category')
    op.drop_table('article')
    op.drop_table('source_has_tag')
    # ### end Alembic commands ###
