"""Modify authors type in Contents table to string

Revision ID: be5f1938cac7
Revises: 52a42ae799ea
Create Date: 2020-04-16 10:47:10.638475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5f1938cac7'
down_revision = '52a42ae799ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
